# To limit exposure to denial of service attacks, change the host in endpoints below from 0.0.0.0 to a specific network interface.
# See https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

  statsd:
    endpoint: 0.0.0.0:8125
    aggregation_interval: 10s
    timer_histogram_mapping:
      - statsd_type: timing
        observer_type: summary
        summary:
         percentiles: [0, 10, 50, 90, 95, 99, 100]
      - statsd_type: distribution
        observer_type: summary
        summary:
         percentiles: [0, 10, 50, 90, 95, 99, 100]

    
processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlphttp/victoriametrics:
    endpoint: http://victoriametrics:8428/opentelemetry
    compression: gzip
    encoding: proto
    tls:
      insecure: true

service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/victoriametrics]

    metrics:
      receivers: [otlp, statsd, prometheus]
      processors: [batch]
      exporters: [otlphttp/victoriametrics]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

  extensions: [health_check, pprof, zpages]
