services:
  victoriametrics:
    image: docker.io/victoriametrics/victoria-metrics:latest
    # network_mode: host
    ports:
      - 8428:8428
    volumes:
      - victoriametrics_data:/victoria-metrics-data
  otel_collector:
    image: docker.io/otel/opentelemetry-collector-contrib:latest
    # network_mode: host
    ports:
      - 4317:4317
      - 4318:4318
      - 8125:8125/udp
    volumes:
      - type: bind
        source: ./collector-config.yaml
        target: /etc/otelcol-contrib/config.yaml
        read_only: true
  grafana:
    # network_mode: host
    image: docker.io/grafana/grafana-oss:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-provisioning-victoriametrics.yaml:/etc/grafana/provisioning/datasources/vm.yaml
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/download/v0.9.0/victoriametrics-datasource-v0.9.0.zip;victoriametrics-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=victoriametrics-datasource
volumes:
  victoriametrics_data:
  grafana_data:
